"use strict";
exports.__esModule = true;
require("./polyfill");
var renderer_1 = require("./renderer");
exports.AwtkRender = renderer_1["default"];
var fixParentChildComponent_1 = require("./utils/fixParentChildComponent");
exports.setParentWidget = fixParentChildComponent_1.setParentWidget;
var awtk_1 = require("./native/awtk");
exports.TEventType = awtk_1.TEventType;
var t_button = "t_button";
exports.t_button = t_button;
var t_window = "t_window";
exports.t_window = t_window;
